/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserRouteRouteImport } from './routes/user/route'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserProfileRouteImport } from './routes/user/profile'
import { Route as UserDashboardRouteImport } from './routes/user/dashboard'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthSignupIndexRouteImport } from './routes/auth/signup/index'
import { Route as AuthResetPasswordIndexRouteImport } from './routes/auth/reset-password/index'
import { Route as AuthForgotPasswordIndexRouteImport } from './routes/auth/forgot-password/index'
import { Route as AuthSignupVerifyOtpRouteImport } from './routes/auth/signup/verify-otp'
import { Route as AuthForgotPasswordVerifyOtpRouteImport } from './routes/auth/forgot-password/verify-otp'

const UserRouteRoute = UserRouteRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserProfileRoute = UserProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => UserRouteRoute,
} as any)
const UserDashboardRoute = UserDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => UserRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignupIndexRoute = AuthSignupIndexRouteImport.update({
  id: '/signup/',
  path: '/signup/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthResetPasswordIndexRoute = AuthResetPasswordIndexRouteImport.update({
  id: '/reset-password/',
  path: '/reset-password/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthForgotPasswordIndexRoute = AuthForgotPasswordIndexRouteImport.update({
  id: '/forgot-password/',
  path: '/forgot-password/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignupVerifyOtpRoute = AuthSignupVerifyOtpRouteImport.update({
  id: '/signup/verify-otp',
  path: '/signup/verify-otp',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthForgotPasswordVerifyOtpRoute =
  AuthForgotPasswordVerifyOtpRouteImport.update({
    id: '/forgot-password/verify-otp',
    path: '/forgot-password/verify-otp',
    getParentRoute: () => AuthRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/user': typeof UserRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/user/dashboard': typeof UserDashboardRoute
  '/user/profile': typeof UserProfileRoute
  '/auth/forgot-password/verify-otp': typeof AuthForgotPasswordVerifyOtpRoute
  '/auth/signup/verify-otp': typeof AuthSignupVerifyOtpRoute
  '/auth/forgot-password': typeof AuthForgotPasswordIndexRoute
  '/auth/reset-password': typeof AuthResetPasswordIndexRoute
  '/auth/signup': typeof AuthSignupIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/user': typeof UserRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/user/dashboard': typeof UserDashboardRoute
  '/user/profile': typeof UserProfileRoute
  '/auth/forgot-password/verify-otp': typeof AuthForgotPasswordVerifyOtpRoute
  '/auth/signup/verify-otp': typeof AuthSignupVerifyOtpRoute
  '/auth/forgot-password': typeof AuthForgotPasswordIndexRoute
  '/auth/reset-password': typeof AuthResetPasswordIndexRoute
  '/auth/signup': typeof AuthSignupIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/user': typeof UserRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/user/dashboard': typeof UserDashboardRoute
  '/user/profile': typeof UserProfileRoute
  '/auth/forgot-password/verify-otp': typeof AuthForgotPasswordVerifyOtpRoute
  '/auth/signup/verify-otp': typeof AuthSignupVerifyOtpRoute
  '/auth/forgot-password/': typeof AuthForgotPasswordIndexRoute
  '/auth/reset-password/': typeof AuthResetPasswordIndexRoute
  '/auth/signup/': typeof AuthSignupIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/user'
    | '/auth/login'
    | '/user/dashboard'
    | '/user/profile'
    | '/auth/forgot-password/verify-otp'
    | '/auth/signup/verify-otp'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/signup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/user'
    | '/auth/login'
    | '/user/dashboard'
    | '/user/profile'
    | '/auth/forgot-password/verify-otp'
    | '/auth/signup/verify-otp'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/signup'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/user'
    | '/auth/login'
    | '/user/dashboard'
    | '/user/profile'
    | '/auth/forgot-password/verify-otp'
    | '/auth/signup/verify-otp'
    | '/auth/forgot-password/'
    | '/auth/reset-password/'
    | '/auth/signup/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  UserRouteRoute: typeof UserRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/user': {
      id: '/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/profile': {
      id: '/user/profile'
      path: '/profile'
      fullPath: '/user/profile'
      preLoaderRoute: typeof UserProfileRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/user/dashboard': {
      id: '/user/dashboard'
      path: '/dashboard'
      fullPath: '/user/dashboard'
      preLoaderRoute: typeof UserDashboardRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/signup/': {
      id: '/auth/signup/'
      path: '/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/reset-password/': {
      id: '/auth/reset-password/'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/forgot-password/': {
      id: '/auth/forgot-password/'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/signup/verify-otp': {
      id: '/auth/signup/verify-otp'
      path: '/signup/verify-otp'
      fullPath: '/auth/signup/verify-otp'
      preLoaderRoute: typeof AuthSignupVerifyOtpRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/forgot-password/verify-otp': {
      id: '/auth/forgot-password/verify-otp'
      path: '/forgot-password/verify-otp'
      fullPath: '/auth/forgot-password/verify-otp'
      preLoaderRoute: typeof AuthForgotPasswordVerifyOtpRouteImport
      parentRoute: typeof AuthRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthForgotPasswordVerifyOtpRoute: typeof AuthForgotPasswordVerifyOtpRoute
  AuthSignupVerifyOtpRoute: typeof AuthSignupVerifyOtpRoute
  AuthForgotPasswordIndexRoute: typeof AuthForgotPasswordIndexRoute
  AuthResetPasswordIndexRoute: typeof AuthResetPasswordIndexRoute
  AuthSignupIndexRoute: typeof AuthSignupIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthForgotPasswordVerifyOtpRoute: AuthForgotPasswordVerifyOtpRoute,
  AuthSignupVerifyOtpRoute: AuthSignupVerifyOtpRoute,
  AuthForgotPasswordIndexRoute: AuthForgotPasswordIndexRoute,
  AuthResetPasswordIndexRoute: AuthResetPasswordIndexRoute,
  AuthSignupIndexRoute: AuthSignupIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface UserRouteRouteChildren {
  UserDashboardRoute: typeof UserDashboardRoute
  UserProfileRoute: typeof UserProfileRoute
}

const UserRouteRouteChildren: UserRouteRouteChildren = {
  UserDashboardRoute: UserDashboardRoute,
  UserProfileRoute: UserProfileRoute,
}

const UserRouteRouteWithChildren = UserRouteRoute._addFileChildren(
  UserRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  UserRouteRoute: UserRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
