/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserRouteImport } from './routes/user'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdminAuthRouteRouteImport } from './routes/_admin-auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserProfileRouteImport } from './routes/user/profile'
import { Route as UserKycVerificationRouteImport } from './routes/user/kyc-verification'
import { Route as UserHomeRouteImport } from './routes/user/home'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AdminUsersManagementRouteImport } from './routes/admin/users-management'
import { Route as AdminTransactionsManagementRouteImport } from './routes/admin/transactions-management'
import { Route as AdminKycManagementRouteImport } from './routes/admin/kyc-management'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as UserWalletIndexRouteImport } from './routes/user/wallet/index'
import { Route as UserPortfolioIndexRouteImport } from './routes/user/portfolio/index'
import { Route as UserMutualFundsIndexRouteImport } from './routes/user/mutual-funds/index'
import { Route as AuthSignupIndexRouteImport } from './routes/auth/signup/index'
import { Route as AuthResetPasswordIndexRouteImport } from './routes/auth/reset-password/index'
import { Route as AuthForgotPasswordIndexRouteImport } from './routes/auth/forgot-password/index'
import { Route as UserWalletWithdrawRouteImport } from './routes/user/wallet/withdraw'
import { Route as UserWalletAddToWalletRouteImport } from './routes/user/wallet/add-to-wallet'
import { Route as UserPortfolioRedeemProfitRouteImport } from './routes/user/portfolio/redeem-profit'
import { Route as UserMutualFundsSchemeCodeRouteImport } from './routes/user/mutual-funds/$schemeCode'
import { Route as UserPaymentPaymentSuccessRouteImport } from './routes/user/_payment/payment-success'
import { Route as UserPaymentPaymentFailedRouteImport } from './routes/user/_payment/payment-failed'
import { Route as AuthSignupVerifyOtpRouteImport } from './routes/auth/signup/verify-otp'
import { Route as AuthForgotPasswordVerifyOtpRouteImport } from './routes/auth/forgot-password/verify-otp'
import { Route as AdminViewKycKycIdRouteImport } from './routes/admin/view-kyc/$kycId'
import { Route as AdminMutualFundMutualFundsManagementRouteImport } from './routes/admin/_mutual-fund/mutual-funds-management'
import { Route as AdminMutualFundAddNewFundRouteImport } from './routes/admin/_mutual-fund/add-new-fund'
import { Route as AdminAuthAdminAuthenticationIndexRouteImport } from './routes/_admin-auth/admin/authentication/index'
import { Route as AdminAuthAdminAuthenticationVerifyOtpRouteImport } from './routes/_admin-auth/admin/authentication/verify-otp'

const UserRoute = UserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthRouteRoute = AdminAuthRouteRouteImport.update({
  id: '/_admin-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserProfileRoute = UserProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => UserRoute,
} as any)
const UserKycVerificationRoute = UserKycVerificationRouteImport.update({
  id: '/kyc-verification',
  path: '/kyc-verification',
  getParentRoute: () => UserRoute,
} as any)
const UserHomeRoute = UserHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => UserRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AdminUsersManagementRoute = AdminUsersManagementRouteImport.update({
  id: '/users-management',
  path: '/users-management',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTransactionsManagementRoute =
  AdminTransactionsManagementRouteImport.update({
    id: '/transactions-management',
    path: '/transactions-management',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminKycManagementRoute = AdminKycManagementRouteImport.update({
  id: '/kyc-management',
  path: '/kyc-management',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const UserWalletIndexRoute = UserWalletIndexRouteImport.update({
  id: '/wallet/',
  path: '/wallet/',
  getParentRoute: () => UserRoute,
} as any)
const UserPortfolioIndexRoute = UserPortfolioIndexRouteImport.update({
  id: '/portfolio/',
  path: '/portfolio/',
  getParentRoute: () => UserRoute,
} as any)
const UserMutualFundsIndexRoute = UserMutualFundsIndexRouteImport.update({
  id: '/mutual-funds/',
  path: '/mutual-funds/',
  getParentRoute: () => UserRoute,
} as any)
const AuthSignupIndexRoute = AuthSignupIndexRouteImport.update({
  id: '/signup/',
  path: '/signup/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordIndexRoute = AuthResetPasswordIndexRouteImport.update({
  id: '/reset-password/',
  path: '/reset-password/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordIndexRoute = AuthForgotPasswordIndexRouteImport.update({
  id: '/forgot-password/',
  path: '/forgot-password/',
  getParentRoute: () => AuthRoute,
} as any)
const UserWalletWithdrawRoute = UserWalletWithdrawRouteImport.update({
  id: '/wallet/withdraw',
  path: '/wallet/withdraw',
  getParentRoute: () => UserRoute,
} as any)
const UserWalletAddToWalletRoute = UserWalletAddToWalletRouteImport.update({
  id: '/wallet/add-to-wallet',
  path: '/wallet/add-to-wallet',
  getParentRoute: () => UserRoute,
} as any)
const UserPortfolioRedeemProfitRoute =
  UserPortfolioRedeemProfitRouteImport.update({
    id: '/portfolio/redeem-profit',
    path: '/portfolio/redeem-profit',
    getParentRoute: () => UserRoute,
  } as any)
const UserMutualFundsSchemeCodeRoute =
  UserMutualFundsSchemeCodeRouteImport.update({
    id: '/mutual-funds/$schemeCode',
    path: '/mutual-funds/$schemeCode',
    getParentRoute: () => UserRoute,
  } as any)
const UserPaymentPaymentSuccessRoute =
  UserPaymentPaymentSuccessRouteImport.update({
    id: '/_payment/payment-success',
    path: '/payment-success',
    getParentRoute: () => UserRoute,
  } as any)
const UserPaymentPaymentFailedRoute =
  UserPaymentPaymentFailedRouteImport.update({
    id: '/_payment/payment-failed',
    path: '/payment-failed',
    getParentRoute: () => UserRoute,
  } as any)
const AuthSignupVerifyOtpRoute = AuthSignupVerifyOtpRouteImport.update({
  id: '/signup/verify-otp',
  path: '/signup/verify-otp',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordVerifyOtpRoute =
  AuthForgotPasswordVerifyOtpRouteImport.update({
    id: '/forgot-password/verify-otp',
    path: '/forgot-password/verify-otp',
    getParentRoute: () => AuthRoute,
  } as any)
const AdminViewKycKycIdRoute = AdminViewKycKycIdRouteImport.update({
  id: '/view-kyc/$kycId',
  path: '/view-kyc/$kycId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMutualFundMutualFundsManagementRoute =
  AdminMutualFundMutualFundsManagementRouteImport.update({
    id: '/_mutual-fund/mutual-funds-management',
    path: '/mutual-funds-management',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminMutualFundAddNewFundRoute =
  AdminMutualFundAddNewFundRouteImport.update({
    id: '/_mutual-fund/add-new-fund',
    path: '/add-new-fund',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAuthAdminAuthenticationIndexRoute =
  AdminAuthAdminAuthenticationIndexRouteImport.update({
    id: '/admin/authentication/',
    path: '/admin/authentication/',
    getParentRoute: () => AdminAuthRouteRoute,
  } as any)
const AdminAuthAdminAuthenticationVerifyOtpRoute =
  AdminAuthAdminAuthenticationVerifyOtpRouteImport.update({
    id: '/admin/authentication/verify-otp',
    path: '/admin/authentication/verify-otp',
    getParentRoute: () => AdminAuthRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/user': typeof UserRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/kyc-management': typeof AdminKycManagementRoute
  '/admin/transactions-management': typeof AdminTransactionsManagementRoute
  '/admin/users-management': typeof AdminUsersManagementRoute
  '/auth/login': typeof AuthLoginRoute
  '/user/home': typeof UserHomeRoute
  '/user/kyc-verification': typeof UserKycVerificationRoute
  '/user/profile': typeof UserProfileRoute
  '/admin/add-new-fund': typeof AdminMutualFundAddNewFundRoute
  '/admin/mutual-funds-management': typeof AdminMutualFundMutualFundsManagementRoute
  '/admin/view-kyc/$kycId': typeof AdminViewKycKycIdRoute
  '/auth/forgot-password/verify-otp': typeof AuthForgotPasswordVerifyOtpRoute
  '/auth/signup/verify-otp': typeof AuthSignupVerifyOtpRoute
  '/user/payment-failed': typeof UserPaymentPaymentFailedRoute
  '/user/payment-success': typeof UserPaymentPaymentSuccessRoute
  '/user/mutual-funds/$schemeCode': typeof UserMutualFundsSchemeCodeRoute
  '/user/portfolio/redeem-profit': typeof UserPortfolioRedeemProfitRoute
  '/user/wallet/add-to-wallet': typeof UserWalletAddToWalletRoute
  '/user/wallet/withdraw': typeof UserWalletWithdrawRoute
  '/auth/forgot-password': typeof AuthForgotPasswordIndexRoute
  '/auth/reset-password': typeof AuthResetPasswordIndexRoute
  '/auth/signup': typeof AuthSignupIndexRoute
  '/user/mutual-funds': typeof UserMutualFundsIndexRoute
  '/user/portfolio': typeof UserPortfolioIndexRoute
  '/user/wallet': typeof UserWalletIndexRoute
  '/admin/authentication/verify-otp': typeof AdminAuthAdminAuthenticationVerifyOtpRoute
  '/admin/authentication': typeof AdminAuthAdminAuthenticationIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/user': typeof UserRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/kyc-management': typeof AdminKycManagementRoute
  '/admin/transactions-management': typeof AdminTransactionsManagementRoute
  '/admin/users-management': typeof AdminUsersManagementRoute
  '/auth/login': typeof AuthLoginRoute
  '/user/home': typeof UserHomeRoute
  '/user/kyc-verification': typeof UserKycVerificationRoute
  '/user/profile': typeof UserProfileRoute
  '/admin/add-new-fund': typeof AdminMutualFundAddNewFundRoute
  '/admin/mutual-funds-management': typeof AdminMutualFundMutualFundsManagementRoute
  '/admin/view-kyc/$kycId': typeof AdminViewKycKycIdRoute
  '/auth/forgot-password/verify-otp': typeof AuthForgotPasswordVerifyOtpRoute
  '/auth/signup/verify-otp': typeof AuthSignupVerifyOtpRoute
  '/user/payment-failed': typeof UserPaymentPaymentFailedRoute
  '/user/payment-success': typeof UserPaymentPaymentSuccessRoute
  '/user/mutual-funds/$schemeCode': typeof UserMutualFundsSchemeCodeRoute
  '/user/portfolio/redeem-profit': typeof UserPortfolioRedeemProfitRoute
  '/user/wallet/add-to-wallet': typeof UserWalletAddToWalletRoute
  '/user/wallet/withdraw': typeof UserWalletWithdrawRoute
  '/auth/forgot-password': typeof AuthForgotPasswordIndexRoute
  '/auth/reset-password': typeof AuthResetPasswordIndexRoute
  '/auth/signup': typeof AuthSignupIndexRoute
  '/user/mutual-funds': typeof UserMutualFundsIndexRoute
  '/user/portfolio': typeof UserPortfolioIndexRoute
  '/user/wallet': typeof UserWalletIndexRoute
  '/admin/authentication/verify-otp': typeof AdminAuthAdminAuthenticationVerifyOtpRoute
  '/admin/authentication': typeof AdminAuthAdminAuthenticationIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin-auth': typeof AdminAuthRouteRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/user': typeof UserRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/kyc-management': typeof AdminKycManagementRoute
  '/admin/transactions-management': typeof AdminTransactionsManagementRoute
  '/admin/users-management': typeof AdminUsersManagementRoute
  '/auth/login': typeof AuthLoginRoute
  '/user/home': typeof UserHomeRoute
  '/user/kyc-verification': typeof UserKycVerificationRoute
  '/user/profile': typeof UserProfileRoute
  '/admin/_mutual-fund/add-new-fund': typeof AdminMutualFundAddNewFundRoute
  '/admin/_mutual-fund/mutual-funds-management': typeof AdminMutualFundMutualFundsManagementRoute
  '/admin/view-kyc/$kycId': typeof AdminViewKycKycIdRoute
  '/auth/forgot-password/verify-otp': typeof AuthForgotPasswordVerifyOtpRoute
  '/auth/signup/verify-otp': typeof AuthSignupVerifyOtpRoute
  '/user/_payment/payment-failed': typeof UserPaymentPaymentFailedRoute
  '/user/_payment/payment-success': typeof UserPaymentPaymentSuccessRoute
  '/user/mutual-funds/$schemeCode': typeof UserMutualFundsSchemeCodeRoute
  '/user/portfolio/redeem-profit': typeof UserPortfolioRedeemProfitRoute
  '/user/wallet/add-to-wallet': typeof UserWalletAddToWalletRoute
  '/user/wallet/withdraw': typeof UserWalletWithdrawRoute
  '/auth/forgot-password/': typeof AuthForgotPasswordIndexRoute
  '/auth/reset-password/': typeof AuthResetPasswordIndexRoute
  '/auth/signup/': typeof AuthSignupIndexRoute
  '/user/mutual-funds/': typeof UserMutualFundsIndexRoute
  '/user/portfolio/': typeof UserPortfolioIndexRoute
  '/user/wallet/': typeof UserWalletIndexRoute
  '/_admin-auth/admin/authentication/verify-otp': typeof AdminAuthAdminAuthenticationVerifyOtpRoute
  '/_admin-auth/admin/authentication/': typeof AdminAuthAdminAuthenticationIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/user'
    | '/admin/dashboard'
    | '/admin/kyc-management'
    | '/admin/transactions-management'
    | '/admin/users-management'
    | '/auth/login'
    | '/user/home'
    | '/user/kyc-verification'
    | '/user/profile'
    | '/admin/add-new-fund'
    | '/admin/mutual-funds-management'
    | '/admin/view-kyc/$kycId'
    | '/auth/forgot-password/verify-otp'
    | '/auth/signup/verify-otp'
    | '/user/payment-failed'
    | '/user/payment-success'
    | '/user/mutual-funds/$schemeCode'
    | '/user/portfolio/redeem-profit'
    | '/user/wallet/add-to-wallet'
    | '/user/wallet/withdraw'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/user/mutual-funds'
    | '/user/portfolio'
    | '/user/wallet'
    | '/admin/authentication/verify-otp'
    | '/admin/authentication'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/user'
    | '/admin/dashboard'
    | '/admin/kyc-management'
    | '/admin/transactions-management'
    | '/admin/users-management'
    | '/auth/login'
    | '/user/home'
    | '/user/kyc-verification'
    | '/user/profile'
    | '/admin/add-new-fund'
    | '/admin/mutual-funds-management'
    | '/admin/view-kyc/$kycId'
    | '/auth/forgot-password/verify-otp'
    | '/auth/signup/verify-otp'
    | '/user/payment-failed'
    | '/user/payment-success'
    | '/user/mutual-funds/$schemeCode'
    | '/user/portfolio/redeem-profit'
    | '/user/wallet/add-to-wallet'
    | '/user/wallet/withdraw'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/user/mutual-funds'
    | '/user/portfolio'
    | '/user/wallet'
    | '/admin/authentication/verify-otp'
    | '/admin/authentication'
  id:
    | '__root__'
    | '/'
    | '/_admin-auth'
    | '/admin'
    | '/auth'
    | '/user'
    | '/admin/dashboard'
    | '/admin/kyc-management'
    | '/admin/transactions-management'
    | '/admin/users-management'
    | '/auth/login'
    | '/user/home'
    | '/user/kyc-verification'
    | '/user/profile'
    | '/admin/_mutual-fund/add-new-fund'
    | '/admin/_mutual-fund/mutual-funds-management'
    | '/admin/view-kyc/$kycId'
    | '/auth/forgot-password/verify-otp'
    | '/auth/signup/verify-otp'
    | '/user/_payment/payment-failed'
    | '/user/_payment/payment-success'
    | '/user/mutual-funds/$schemeCode'
    | '/user/portfolio/redeem-profit'
    | '/user/wallet/add-to-wallet'
    | '/user/wallet/withdraw'
    | '/auth/forgot-password/'
    | '/auth/reset-password/'
    | '/auth/signup/'
    | '/user/mutual-funds/'
    | '/user/portfolio/'
    | '/user/wallet/'
    | '/_admin-auth/admin/authentication/verify-otp'
    | '/_admin-auth/admin/authentication/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminAuthRouteRoute: typeof AdminAuthRouteRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  UserRoute: typeof UserRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/user': {
      id: '/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin-auth': {
      id: '/_admin-auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AdminAuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/profile': {
      id: '/user/profile'
      path: '/profile'
      fullPath: '/user/profile'
      preLoaderRoute: typeof UserProfileRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/kyc-verification': {
      id: '/user/kyc-verification'
      path: '/kyc-verification'
      fullPath: '/user/kyc-verification'
      preLoaderRoute: typeof UserKycVerificationRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/home': {
      id: '/user/home'
      path: '/home'
      fullPath: '/user/home'
      preLoaderRoute: typeof UserHomeRouteImport
      parentRoute: typeof UserRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/admin/users-management': {
      id: '/admin/users-management'
      path: '/users-management'
      fullPath: '/admin/users-management'
      preLoaderRoute: typeof AdminUsersManagementRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/transactions-management': {
      id: '/admin/transactions-management'
      path: '/transactions-management'
      fullPath: '/admin/transactions-management'
      preLoaderRoute: typeof AdminTransactionsManagementRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/kyc-management': {
      id: '/admin/kyc-management'
      path: '/kyc-management'
      fullPath: '/admin/kyc-management'
      preLoaderRoute: typeof AdminKycManagementRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/user/wallet/': {
      id: '/user/wallet/'
      path: '/wallet'
      fullPath: '/user/wallet'
      preLoaderRoute: typeof UserWalletIndexRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/portfolio/': {
      id: '/user/portfolio/'
      path: '/portfolio'
      fullPath: '/user/portfolio'
      preLoaderRoute: typeof UserPortfolioIndexRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/mutual-funds/': {
      id: '/user/mutual-funds/'
      path: '/mutual-funds'
      fullPath: '/user/mutual-funds'
      preLoaderRoute: typeof UserMutualFundsIndexRouteImport
      parentRoute: typeof UserRoute
    }
    '/auth/signup/': {
      id: '/auth/signup/'
      path: '/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/reset-password/': {
      id: '/auth/reset-password/'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/forgot-password/': {
      id: '/auth/forgot-password/'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/user/wallet/withdraw': {
      id: '/user/wallet/withdraw'
      path: '/wallet/withdraw'
      fullPath: '/user/wallet/withdraw'
      preLoaderRoute: typeof UserWalletWithdrawRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/wallet/add-to-wallet': {
      id: '/user/wallet/add-to-wallet'
      path: '/wallet/add-to-wallet'
      fullPath: '/user/wallet/add-to-wallet'
      preLoaderRoute: typeof UserWalletAddToWalletRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/portfolio/redeem-profit': {
      id: '/user/portfolio/redeem-profit'
      path: '/portfolio/redeem-profit'
      fullPath: '/user/portfolio/redeem-profit'
      preLoaderRoute: typeof UserPortfolioRedeemProfitRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/mutual-funds/$schemeCode': {
      id: '/user/mutual-funds/$schemeCode'
      path: '/mutual-funds/$schemeCode'
      fullPath: '/user/mutual-funds/$schemeCode'
      preLoaderRoute: typeof UserMutualFundsSchemeCodeRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/_payment/payment-success': {
      id: '/user/_payment/payment-success'
      path: '/payment-success'
      fullPath: '/user/payment-success'
      preLoaderRoute: typeof UserPaymentPaymentSuccessRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/_payment/payment-failed': {
      id: '/user/_payment/payment-failed'
      path: '/payment-failed'
      fullPath: '/user/payment-failed'
      preLoaderRoute: typeof UserPaymentPaymentFailedRouteImport
      parentRoute: typeof UserRoute
    }
    '/auth/signup/verify-otp': {
      id: '/auth/signup/verify-otp'
      path: '/signup/verify-otp'
      fullPath: '/auth/signup/verify-otp'
      preLoaderRoute: typeof AuthSignupVerifyOtpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/forgot-password/verify-otp': {
      id: '/auth/forgot-password/verify-otp'
      path: '/forgot-password/verify-otp'
      fullPath: '/auth/forgot-password/verify-otp'
      preLoaderRoute: typeof AuthForgotPasswordVerifyOtpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/admin/view-kyc/$kycId': {
      id: '/admin/view-kyc/$kycId'
      path: '/view-kyc/$kycId'
      fullPath: '/admin/view-kyc/$kycId'
      preLoaderRoute: typeof AdminViewKycKycIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/_mutual-fund/mutual-funds-management': {
      id: '/admin/_mutual-fund/mutual-funds-management'
      path: '/mutual-funds-management'
      fullPath: '/admin/mutual-funds-management'
      preLoaderRoute: typeof AdminMutualFundMutualFundsManagementRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/_mutual-fund/add-new-fund': {
      id: '/admin/_mutual-fund/add-new-fund'
      path: '/add-new-fund'
      fullPath: '/admin/add-new-fund'
      preLoaderRoute: typeof AdminMutualFundAddNewFundRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin-auth/admin/authentication/': {
      id: '/_admin-auth/admin/authentication/'
      path: '/admin/authentication'
      fullPath: '/admin/authentication'
      preLoaderRoute: typeof AdminAuthAdminAuthenticationIndexRouteImport
      parentRoute: typeof AdminAuthRouteRoute
    }
    '/_admin-auth/admin/authentication/verify-otp': {
      id: '/_admin-auth/admin/authentication/verify-otp'
      path: '/admin/authentication/verify-otp'
      fullPath: '/admin/authentication/verify-otp'
      preLoaderRoute: typeof AdminAuthAdminAuthenticationVerifyOtpRouteImport
      parentRoute: typeof AdminAuthRouteRoute
    }
  }
}

interface AdminAuthRouteRouteChildren {
  AdminAuthAdminAuthenticationVerifyOtpRoute: typeof AdminAuthAdminAuthenticationVerifyOtpRoute
  AdminAuthAdminAuthenticationIndexRoute: typeof AdminAuthAdminAuthenticationIndexRoute
}

const AdminAuthRouteRouteChildren: AdminAuthRouteRouteChildren = {
  AdminAuthAdminAuthenticationVerifyOtpRoute:
    AdminAuthAdminAuthenticationVerifyOtpRoute,
  AdminAuthAdminAuthenticationIndexRoute:
    AdminAuthAdminAuthenticationIndexRoute,
}

const AdminAuthRouteRouteWithChildren = AdminAuthRouteRoute._addFileChildren(
  AdminAuthRouteRouteChildren,
)

interface AdminRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminKycManagementRoute: typeof AdminKycManagementRoute
  AdminTransactionsManagementRoute: typeof AdminTransactionsManagementRoute
  AdminUsersManagementRoute: typeof AdminUsersManagementRoute
  AdminMutualFundAddNewFundRoute: typeof AdminMutualFundAddNewFundRoute
  AdminMutualFundMutualFundsManagementRoute: typeof AdminMutualFundMutualFundsManagementRoute
  AdminViewKycKycIdRoute: typeof AdminViewKycKycIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDashboardRoute: AdminDashboardRoute,
  AdminKycManagementRoute: AdminKycManagementRoute,
  AdminTransactionsManagementRoute: AdminTransactionsManagementRoute,
  AdminUsersManagementRoute: AdminUsersManagementRoute,
  AdminMutualFundAddNewFundRoute: AdminMutualFundAddNewFundRoute,
  AdminMutualFundMutualFundsManagementRoute:
    AdminMutualFundMutualFundsManagementRoute,
  AdminViewKycKycIdRoute: AdminViewKycKycIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthForgotPasswordVerifyOtpRoute: typeof AuthForgotPasswordVerifyOtpRoute
  AuthSignupVerifyOtpRoute: typeof AuthSignupVerifyOtpRoute
  AuthForgotPasswordIndexRoute: typeof AuthForgotPasswordIndexRoute
  AuthResetPasswordIndexRoute: typeof AuthResetPasswordIndexRoute
  AuthSignupIndexRoute: typeof AuthSignupIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthForgotPasswordVerifyOtpRoute: AuthForgotPasswordVerifyOtpRoute,
  AuthSignupVerifyOtpRoute: AuthSignupVerifyOtpRoute,
  AuthForgotPasswordIndexRoute: AuthForgotPasswordIndexRoute,
  AuthResetPasswordIndexRoute: AuthResetPasswordIndexRoute,
  AuthSignupIndexRoute: AuthSignupIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface UserRouteChildren {
  UserHomeRoute: typeof UserHomeRoute
  UserKycVerificationRoute: typeof UserKycVerificationRoute
  UserProfileRoute: typeof UserProfileRoute
  UserPaymentPaymentFailedRoute: typeof UserPaymentPaymentFailedRoute
  UserPaymentPaymentSuccessRoute: typeof UserPaymentPaymentSuccessRoute
  UserMutualFundsSchemeCodeRoute: typeof UserMutualFundsSchemeCodeRoute
  UserPortfolioRedeemProfitRoute: typeof UserPortfolioRedeemProfitRoute
  UserWalletAddToWalletRoute: typeof UserWalletAddToWalletRoute
  UserWalletWithdrawRoute: typeof UserWalletWithdrawRoute
  UserMutualFundsIndexRoute: typeof UserMutualFundsIndexRoute
  UserPortfolioIndexRoute: typeof UserPortfolioIndexRoute
  UserWalletIndexRoute: typeof UserWalletIndexRoute
}

const UserRouteChildren: UserRouteChildren = {
  UserHomeRoute: UserHomeRoute,
  UserKycVerificationRoute: UserKycVerificationRoute,
  UserProfileRoute: UserProfileRoute,
  UserPaymentPaymentFailedRoute: UserPaymentPaymentFailedRoute,
  UserPaymentPaymentSuccessRoute: UserPaymentPaymentSuccessRoute,
  UserMutualFundsSchemeCodeRoute: UserMutualFundsSchemeCodeRoute,
  UserPortfolioRedeemProfitRoute: UserPortfolioRedeemProfitRoute,
  UserWalletAddToWalletRoute: UserWalletAddToWalletRoute,
  UserWalletWithdrawRoute: UserWalletWithdrawRoute,
  UserMutualFundsIndexRoute: UserMutualFundsIndexRoute,
  UserPortfolioIndexRoute: UserPortfolioIndexRoute,
  UserWalletIndexRoute: UserWalletIndexRoute,
}

const UserRouteWithChildren = UserRoute._addFileChildren(UserRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminAuthRouteRoute: AdminAuthRouteRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  UserRoute: UserRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
