export enum SipFailureReason {
  // 🔹 Mandate / Bank issues
  MANDATE_NOT_FOUND = 'MANDATE_NOT_FOUND',
  MANDATE_INACTIVE = 'MANDATE_INACTIVE',
  MANDATE_EXPIRED = 'MANDATE_EXPIRED',
  MANDATE_LIMIT_EXCEEDED = 'MANDATE_LIMIT_EXCEEDED',
  BANK_ACCOUNT_CLOSED = 'BANK_ACCOUNT_CLOSED',

  // 🔹 Payment failures
  INSUFFICIENT_FUNDS = 'INSUFFICIENT_FUNDS',
  PAYMENT_DECLINED = 'PAYMENT_DECLINED',
  PAYMENT_TIMEOUT = 'PAYMENT_TIMEOUT',
  DUPLICATE_DEBIT = 'DUPLICATE_DEBIT',

  // 🔹 Scheme / AMC issues
  SCHEME_NOT_ACTIVE = 'SCHEME_NOT_ACTIVE',
  SCHEME_NOT_FOUND = 'SCHEME_NOT_FOUND',
  AMC_REJECTED = 'AMC_REJECTED',
  NAV_NOT_AVAILABLE = 'NAV_NOT_AVAILABLE',
  CUTOFF_TIME_MISSED = 'CUTOFF_TIME_MISSED',

  // 🔹 User / compliance issues
  KYC_INCOMPLETE = 'KYC_INCOMPLETE',
  KYC_REJECTED = 'KYC_REJECTED',
  PAN_INVALID = 'PAN_INVALID',
  FATCA_NON_COMPLIANT = 'FATCA_NON_COMPLIANT',

  // 🔹 SIP lifecycle issues
  SIP_PAUSED = 'SIP_PAUSED',
  SIP_CANCELLED = 'SIP_CANCELLED',
  SIP_COMPLETED = 'SIP_COMPLETED',

  // 🔹 System / technical failures
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  PROVIDER_ERROR = 'PROVIDER_ERROR',
  NETWORK_ERROR = 'NETWORK_ERROR',
  TIMEOUT = 'TIMEOUT',

  // 🔹 Fallback
  UNKNOWN = 'UNKNOWN',
}
