export enum Feature {
    EXPENSE_TRACKING = "EXPENSE_TRACKING",
    PORTFOLIO_BASIC = "PORTFOLIO_BASIC",
    MARKET_NEWS = "MARKET_NEWS",
    MF_ONE_TIME = "MF_ONE_TIME",
    CHATBOT_BASIC = "CHATBOT_BASIC",

    SIP_AUTOMATION = "SIP_AUTOMATION",
    STOCK_TRADING = "STOCK_TRADING",
    ALGO_TRADING = "ALGO_TRADING",
    TRADE_EXECUTION_BOT = "TRADE_EXECUTION_BOT",
    AI_CHAT_ADVANCED = "AI_CHAT_ADVANCED",
    PORTFOLIO_ANALYTICS = "PORTFOLIO_ANALYTICS",
    // AI_TRADING_ASSISTANT = "AI_TRADING_ASSISTANT",
    // SMART_SUGGESTIONS = "SMART_SUGGESTIONS"
}