version: "3.8"

services:
  backend:
    build: .
    container_name: three-m-backend
    ports:
    - "9000:9000"
    restart: always
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:7
    container_name: redis-server
    ports:
      - "6379:6379"
    restart: always