import { IStockRepository } from "@application/interfaces/repositories/stock/stock-repository.interface";
import { ContainerModule } from "inversify";
import { STOCK_TYPES } from "./stock.types";
import { StockRepository } from "@infrastructure/databases/repository/stock/stock.repository";
import { IStockWebsocketProvider } from "@application/interfaces/repositories/stock/stock-websocket.interface";
import { IWatchlistRepository } from "@application/interfaces/repositories/stock/watchlist-repository.interface";
import { WatchlistRepository } from "@infrastructure/databases/repository/stock/watchlist.repository";
import { IStockCandleRepository } from "@application/interfaces/repositories/stock/stock-candle-repository.interface";
import { StockCandleRepository } from "@infrastructure/databases/repository/stock/stock-candle.repository";
import { StockWebSocketClient } from "@infrastructure/providers/stocks/stock-websocket.client";
import { IFetchStocksUseCase } from "@application/use_cases/stock/interfaces/fetch-stocks.interface";
import { FetchStocksUseCase } from "@application/use_cases/stock/fetch-stock.usecase";
import { UserStocksController } from "@presentation/http/controllers/stocks/user-stocks.controller";
import { IStockDetailsUseCase } from "@application/use_cases/stock/interfaces/stock-details-usecase.interface";
import { StockDetailsUseCase } from "@application/use_cases/stock/stock-details.usecase";
import { IFetchStockCandlesUseCase } from "@application/use_cases/stock/interfaces/fetch-stock-candles.interface";
import { FetchStockCandlesUseCase } from "@application/use_cases/stock/fetch-stock-candles.usecase";
import { IAddToWatchlistUseCase } from "@application/use_cases/stock/interfaces/add-to-watchlist-usecase.interface";
import { AddToWatchlistUseCase } from "@application/use_cases/stock/add-to-watchlist.usecase";
import { IRemoveFromWatchlistUseCase } from "@application/use_cases/stock/interfaces/remove-from-watchlist-usecase.interface";
import { RemoveFromWatchlistUseCase } from "@application/use_cases/stock/remove-from-watchlist.usecase";
import { IFetchWatchlistUseCase } from "@application/use_cases/stock/interfaces/fetch-watchlist-usecase.interface";
import { FetchWatchlistUseCase } from "@application/use_cases/stock/fetch-watchlist.usecase";
import { IFetchOrderHistoryUseCase } from "@application/use_cases/stock/interfaces/fetch-order-history.interface";
import { FetchOrderHistoryUseCase } from "@application/use_cases/stock/fetch-order-history.usecase";
import { MarketDataService } from "@infrastructure/providers/stocks/market-data.service";
import { WsGateway } from "@presentation/express/websocket/ws.gateway";
import { CandleEngineService } from "@infrastructure/providers/stocks/market-data/services/candle-engine.service";
import { TimeframeAggregatorService } from "@infrastructure/providers/stocks/market-data/services/timeframe-aggregator.service";
import { PollingService } from "@infrastructure/providers/stocks/market-data/services/polling.service";
import { OrdersController } from "@presentation/http/controllers/stocks/orders.controller";
import { MarketBuyOrderUseCase } from "@application/use_cases/stock/market-buy-order.usecase";
import { IMarketBuyOrderUseCase } from "@application/use_cases/stock/interfaces/buy-order-usecase.interface";
import { IMarketSellOrderUseCase } from "@application/use_cases/stock/interfaces/market-sell-order-usecase.interface";
import { MarketSellOrderUseCase } from "@application/use_cases/stock/market-sell-order.usecase";
import { IOrderRepository } from "@application/interfaces/repositories/stock/order-repository.interface";
import { OrderRepository } from "@infrastructure/databases/repository/stock/order.repository";
import { IAlgoStrategyConfigRepository } from "@application/interfaces/repositories/algo/algo-strategy-config-repository.interface";
import { AlgoStrategyConfigRepository } from "@infrastructure/databases/repository/algo-trading/algo-strategy-config.repository";
import { IAdminGetBaseStrategiesUseCase, IAdminUpdateStrategyRiskConfigUseCase } from "@application/use_cases/admin/algo-trading/interfaces/admin-base-strategy-risk.interface";
import { AdminGetBaseStrategiesUseCase } from "@application/use_cases/admin/algo-trading/admin-get-base-strategies.usecase";
import { AdminUpdateStrategyRiskConfigUseCase } from "@application/use_cases/admin/algo-trading/admin-update-strategy-risk-config.usecase";
import { IAdminGetAllTradesUseCase } from "@application/use_cases/admin/trades/interfaces/admin-get-all-trades-usecase.interface";
import { AdminGetAllTradesUseCase } from "@application/use_cases/admin/trades/admin-get-all-trades.usecase";
import { ITradeRepository } from "@application/interfaces/repositories/stock/trade-repository.interface";
import { AlgoTradingController } from "@presentation/http/controllers/algo-trading/algo-trading.controller";
import { GetStrategiesUseCase } from "@application/use_cases/algo-trading/get-strategies.usecase";
import { IAlgoStrategyRepository } from "@application/interfaces/repositories/algo/algo-strategy-repository.interface";
import { AlgoStrategyRepository } from "@infrastructure/databases/repository/algo-trading/algo-strategy.repository";
import { ISaveAlgoStrategyUseCase } from "@application/use_cases/algo-trading/interfaces/save-algo-strategy.interface";
import { SaveAlgoStrategyUseCase } from "@application/use_cases/algo-trading/save-algo-strategy.usecase";
import { IGetActiveStrategyUseCase } from "@application/use_cases/algo-trading/interfaces/get-active-strategy.interface";
import { GetActiveStrategyUseCase } from "@application/use_cases/algo-trading/get-active-strategy.usecase";
import { TurnOnAlgoTradingUseCase } from "@application/use_cases/algo-trading/turn-on-algo-trading.usecase";
import { IAlgoSignalRepository } from "@application/interfaces/repositories/algo/algo-signal-repository.interface";
import { AlgoSignalRepository } from "@infrastructure/databases/repository/algo-trading/algo-signal.repository";
import { IProcessSignalUseCase } from "@application/use_cases/algo-trading/interfaces/process-signal.interface";
import { ProcessSignalUseCase } from "@application/use_cases/algo-trading/process-signal.usecase";
import { IConfirmBuySignalUseCase } from "@application/use_cases/algo-trading/interfaces/confirm-buy-signal.interface";
import { ConfirmBuySignalUseCase } from "@application/use_cases/algo-trading/confirm-buy-signal.usecase";
import { IConfirmSellSignalUseCase } from "@application/use_cases/algo-trading/interfaces/confirm-sell-signal.interface";
import { ConfirmSellSignalUseCase } from "@application/use_cases/algo-trading/confirm-sell-signal.usecase";
import { IMarketDataProvider } from "@application/interfaces/repositories/stock/market-data-provider.interface";
import { YahooProvider } from "@infrastructure/providers/stocks/market-data/providers/yahoo.provider";
import { ITurnOnAlgoTradingUseCase } from "@application/use_cases/algo-trading/interfaces/turn-on-algo-trading.interface";
import { ILimitBuyOrderUseCase } from "@application/use_cases/stock/interfaces/limit-buy-order-usecase.interface";
import { LimitBuyOrderUseCase } from "@application/use_cases/stock/limit-buy-order.usecase";
import { IExecuteLimitBuyOrderUseCase } from "@application/use_cases/stock/interfaces/execute-limit-buy-order.interface";
import { ExecuteLimitBuyOrderUseCase } from "@application/use_cases/stock/execute-limit-buy-order.usecase";
import { ILimitSellOrderUseCase } from "@application/use_cases/stock/interfaces/limit-sell-order-usecase.interface";
import { LimitSellOrderUseCase } from "@application/use_cases/stock/limit-sell-order.usecase";
import { IExecuteLimitSellOrderUseCase } from "@application/use_cases/stock/interfaces/execute-limit-sell-order.interface";
import { ExecuteLimitSellOrderUseCase } from "@application/use_cases/stock/execute-limit-sell-order.usecase";
import { ICancelLimitOrderUseCase } from "@application/use_cases/stock/interfaces/cancel-limit-order-usecase.interface";
import { CancelLimitOrderUseCase } from "@application/use_cases/stock/cancel-limit-order.usecase";
import { IFetchPendingOrdersUseCase } from "@application/use_cases/stock/interfaces/fetch-pending-orders-usecase.interface";
import { FetchPendingOrdersUseCase } from "@application/use_cases/stock/fetch-pending-orders.usecase";
import { IOrderQueue } from "@application/interfaces/services/stocks/order-queue.interface";
import { OrderQueue } from "@infrastructure/providers/stocks/queue/order.queue";
import { OrderWorker } from "@infrastructure/providers/stocks/queue/workers/order.worker";
import { LimitOrderScheduler } from "@infrastructure/providers/stocks/queue/limit-order-scheduler";
import { IExecuteSlTpUseCase } from "@application/use_cases/stock/interfaces/execute-sl-tp.interface";
import { ExecuteSlTpUseCase } from "@application/use_cases/stock/execute-sl-tp.usecase";
import { SlTpOrderWorker } from "@infrastructure/providers/stocks/queue/workers/sl-tp-order.worker";
import { SlTpOrderScheduler } from "@infrastructure/providers/stocks/queue/sl-tp-order.scheduler";
import { IGetMarketMoversUseCase } from "@application/use_cases/stock/interfaces/get-market-movers.interface";
import { GetMarketMoversUseCase } from "@application/use_cases/stock/get-market-movers.usecase";
import { IStrategiesUseCase } from "@application/use_cases/algo-trading/interfaces/get-valid-strategies.interface";
import { StrategiesUseCase } from "@application/use_cases/algo-trading/get-valid-strategies.usecase";
import { IEvaluateStrategyUseCase } from "@application/use_cases/algo-trading/interfaces/evaluate-strategy.interface";
import { EvaluateStrategyUseCase } from "@application/use_cases/algo-trading/evaluate-strategy.usecase";
import { IExecuteMarketBuyOrderUseCase } from "@application/use_cases/stock/interfaces/execute-market-buy-order.interface";
import { ExecuteMarketBuyOrderUseCase } from "@application/use_cases/stock/execute-market-buy-order.usecase";
import { IExecuteMarketSellOrderUseCase } from "@application/use_cases/stock/interfaces/execute-market-sell-order.interface";
import { ExecuteMarketSellOrderUseCase } from "@application/use_cases/stock/execute-market-sell-order.usecase";
import { IStockValidationService } from "@application/services/stock/interfaces/stock-validation.service.interface";
import { StockValidationService } from "@application/services/stock/stock-validation.service";
import { IDispatchLimitOrdersUseCase } from "@application/use_cases/stock/interfaces/dispatch-limit-orders.interface";
import { DispatchLimitOrdersUseCase } from "@application/use_cases/stock/dispatch-limit-orders.usecase";
import { IDispatchSlTpOrdersUseCase } from "@application/use_cases/stock/interfaces/dispatch-sl-tp-orders.interface";
import { DispatchSlTpOrdersUseCase } from "@application/use_cases/stock/dispatch-sl-tp-orders.usecase";
import { IProcessOrderJobUseCase } from "@application/use_cases/stock/interfaces/process-order-job.interface";
import { ProcessOrderJobUseCase } from "@application/use_cases/stock/process-order-job.usecase";

// BullMQ & Queues
import { StrategyQueue } from "@infrastructure/providers/algos/queue/strategy/strategy.queue";
import { StrategyWorker } from "@infrastructure/providers/algos/queue/workers/strategy.worker";
import { SignalWorker } from "@infrastructure/providers/algos/queue/workers/signal.worker";
import { StrategyScheduler } from "@infrastructure/providers/algos/strategy-scheduler";
import { IStrategyQueue } from "@application/interfaces/services/algo-trading/strategy-queue.interface";
import { ISignalQueue } from "@application/interfaces/services/algo-trading/signal-queue.interface";
import { IStrategyScheduler } from "@application/interfaces/services/algo-trading/strategy-scheduler.interface";
import { ITimeframeAggregatorService } from "@application/interfaces/services/stocks/timeframe-aggragator.interface";
import { ICandleEngineService } from "@application/interfaces/services/stocks/candle-engine-service.interface";
import { IPollingService } from "@application/interfaces/services/stocks/polling-service.interface";
import { IMarketDataService } from "@application/interfaces/services/stocks/market-data-service.usecase";
import { IWsGateway } from "@application/interfaces/services/stocks/ws-gateway.interface";
import { ISlTpOrderQueue } from "@application/interfaces/services/stocks/sl-tp-order-queue.interface";
import { SlTpOrderQueue } from "@infrastructure/providers/stocks/queue/sl-tp-order-queue";
import { SignalQueue } from "@infrastructure/providers/algos/queue/signal/signal.queue";
import { TradeRepository } from "@infrastructure/databases/repository/stock/trade.repository";
import { IStockSearchProvider } from "@application/interfaces/repositories/stock/stock-search-provider.interface";
import { TwelveDataSearchProvider } from "@infrastructure/providers/stocks/twelve-data/twelve-data-search.provider";

export const StockModules = new ContainerModule(({ bind }) => {
    bind<IStockRepository>(STOCK_TYPES.StockRepository).to(StockRepository);
    bind<IStockSearchProvider>(STOCK_TYPES.StockSearchProvider).to(TwelveDataSearchProvider);

    bind<IStockWebsocketProvider>(STOCK_TYPES.StockWebSocketClient).to(StockWebSocketClient)
    bind<IFetchStocksUseCase>(STOCK_TYPES.FetchStocksUseCase).to(FetchStocksUseCase);
    bind<UserStocksController>(STOCK_TYPES.UserStocksController).to(UserStocksController);
    bind<IStockDetailsUseCase>(STOCK_TYPES.StockDetailsUseCase).to(StockDetailsUseCase);
    bind<IFetchStockCandlesUseCase>(STOCK_TYPES.FetchStockCandlesUseCase).to(FetchStockCandlesUseCase);

    bind<IMarketDataService>(STOCK_TYPES.MarketDataService).to(MarketDataService);
    bind<IWsGateway>(STOCK_TYPES.WsGateway).to(WsGateway);

    bind<IMarketDataProvider>(STOCK_TYPES.MarketDataProvider).to(YahooProvider);
    bind<IPollingService>(STOCK_TYPES.PollingService).to(PollingService);

    bind<ICandleEngineService>(STOCK_TYPES.CandleEngineService).to(CandleEngineService);
    bind<ITimeframeAggregatorService>(STOCK_TYPES.TimeframeAggregatorService).to(TimeframeAggregatorService);

    bind<OrdersController>(STOCK_TYPES.OrdersController).to(OrdersController);
    bind<IMarketBuyOrderUseCase>(STOCK_TYPES.MarketBuyOrderUseCase).to(MarketBuyOrderUseCase);
    bind<IExecuteMarketBuyOrderUseCase>(STOCK_TYPES.ExecuteMarketBuyOrderUseCase).to(ExecuteMarketBuyOrderUseCase);
    bind<IMarketSellOrderUseCase>(STOCK_TYPES.MarketSellOrderUseCase).to(MarketSellOrderUseCase);
    bind<IExecuteMarketSellOrderUseCase>(STOCK_TYPES.ExecuteMarketSellOrderUseCase).to(ExecuteMarketSellOrderUseCase);
    bind<IStockValidationService>(STOCK_TYPES.StockValidationService).to(StockValidationService);

    bind<ILimitBuyOrderUseCase>(STOCK_TYPES.LimitBuyOrderUseCase).to(LimitBuyOrderUseCase);
    bind<IExecuteLimitBuyOrderUseCase>(STOCK_TYPES.ExecuteLimitBuyOrderUseCase).to(ExecuteLimitBuyOrderUseCase);
    bind<ILimitSellOrderUseCase>(STOCK_TYPES.LimitSellOrderUseCase).to(LimitSellOrderUseCase);
    bind<IExecuteLimitSellOrderUseCase>(STOCK_TYPES.ExecuteLimitSellOrderUseCase).to(ExecuteLimitSellOrderUseCase);
    bind<ICancelLimitOrderUseCase>(STOCK_TYPES.CancelLimitOrderUseCase).to(CancelLimitOrderUseCase);
    bind<IFetchPendingOrdersUseCase>(STOCK_TYPES.FetchPendingOrdersUseCase).to(FetchPendingOrdersUseCase);
    bind<IExecuteSlTpUseCase>(STOCK_TYPES.ExecuteSlTpUseCase).to(ExecuteSlTpUseCase);
    bind<IOrderRepository>(STOCK_TYPES.OrderRepository).to(OrderRepository);
    bind<ITradeRepository>(STOCK_TYPES.TradeRepository).to(TradeRepository);
    bind<IDispatchLimitOrdersUseCase>(STOCK_TYPES.DispatchLimitOrdersUseCase).to(DispatchLimitOrdersUseCase);
    bind<IDispatchSlTpOrdersUseCase>(STOCK_TYPES.DispatchSlTpOrdersUseCase).to(DispatchSlTpOrdersUseCase);
    bind<IProcessOrderJobUseCase>(STOCK_TYPES.ProcessOrderJobUseCase).to(ProcessOrderJobUseCase);

    bind<AlgoTradingController>(STOCK_TYPES.AlgoTradingController).to(AlgoTradingController);
    bind<GetStrategiesUseCase>(STOCK_TYPES.GetStrategiesUseCase).to(GetStrategiesUseCase);
    bind<ISaveAlgoStrategyUseCase>(STOCK_TYPES.SaveAlgoStrategyUseCase).to(SaveAlgoStrategyUseCase);
    bind<IGetActiveStrategyUseCase>(STOCK_TYPES.GetActiveStrategyUseCase).to(GetActiveStrategyUseCase);
    bind<ITurnOnAlgoTradingUseCase>(STOCK_TYPES.TurnOnAlgoTradingUseCase).to(TurnOnAlgoTradingUseCase);
    bind<IAlgoStrategyRepository>(STOCK_TYPES.AlgoStrategyRepository).to(AlgoStrategyRepository);
    bind<IAlgoStrategyConfigRepository>(STOCK_TYPES.AlgoStrategyConfigRepository).to(AlgoStrategyConfigRepository);
    bind<IAdminGetBaseStrategiesUseCase>(STOCK_TYPES.AdminGetBaseStrategiesUseCase).to(AdminGetBaseStrategiesUseCase);
    bind<IAdminUpdateStrategyRiskConfigUseCase>(STOCK_TYPES.AdminUpdateStrategyRiskConfigUseCase).to(AdminUpdateStrategyRiskConfigUseCase);
    bind<IAdminGetAllTradesUseCase>(STOCK_TYPES.AdminGetAllTradesUseCase).to(AdminGetAllTradesUseCase);
    bind<IAlgoSignalRepository>(STOCK_TYPES.AlgoSignalRepository).to(AlgoSignalRepository);
    bind<IProcessSignalUseCase>(STOCK_TYPES.ProcessSignalUseCase).to(ProcessSignalUseCase);
    bind<IConfirmBuySignalUseCase>(STOCK_TYPES.ConfirmBuySignalUseCase).to(ConfirmBuySignalUseCase);
    bind<IConfirmSellSignalUseCase>(STOCK_TYPES.ConfirmSellSignalUseCase).to(ConfirmSellSignalUseCase);
    bind<IStrategiesUseCase>(STOCK_TYPES.StrategiesUseCase).to(StrategiesUseCase);
    bind<IEvaluateStrategyUseCase>(STOCK_TYPES.EvaluateStrategyUseCase).to(EvaluateStrategyUseCase);

    // BullMQ & Queues
    bind<IStrategyQueue>(STOCK_TYPES.StrategyQueue).to(StrategyQueue);
    bind<ISignalQueue>(STOCK_TYPES.SignalQueue).to(SignalQueue);
    bind<StrategyWorker>(STOCK_TYPES.StrategyWorker).to(StrategyWorker);
    bind<SignalWorker>(STOCK_TYPES.SignalWorker).to(SignalWorker);
    bind<OrderWorker>(STOCK_TYPES.OrderWorker).to(OrderWorker);
    bind<IStrategyScheduler>(STOCK_TYPES.StrategyScheduler).to(StrategyScheduler);
    bind<LimitOrderScheduler>(STOCK_TYPES.LimitOrderScheduler).to(LimitOrderScheduler);
    bind<SlTpOrderWorker>(STOCK_TYPES.SlTpOrderWorker).to(SlTpOrderWorker);
    bind<SlTpOrderScheduler>(STOCK_TYPES.SlTpOrderScheduler).to(SlTpOrderScheduler);

    bind<IOrderQueue>(STOCK_TYPES.OrderQueue).to(OrderQueue);
    bind<ISlTpOrderQueue>(STOCK_TYPES.SlTpOrderQueue).to(SlTpOrderQueue);

    // bind<IEngineRunner>(STOCK_TYPES.EngineRunner).to(EngineRunner);
    bind<IWatchlistRepository>(STOCK_TYPES.WatchlistRepository).to(WatchlistRepository);
    bind<IStockCandleRepository>(STOCK_TYPES.StockCandleRepository).to(StockCandleRepository);
    bind<IAddToWatchlistUseCase>(STOCK_TYPES.AddToWatchlistUseCase).to(AddToWatchlistUseCase);
    bind<IRemoveFromWatchlistUseCase>(STOCK_TYPES.RemoveFromWatchlistUseCase).to(RemoveFromWatchlistUseCase);
    bind<IFetchWatchlistUseCase>(STOCK_TYPES.FetchWatchlistUseCase).to(FetchWatchlistUseCase);
    bind<IGetMarketMoversUseCase>(STOCK_TYPES.GetMarketMoversUseCase).to(GetMarketMoversUseCase);
    bind<IFetchOrderHistoryUseCase>(STOCK_TYPES.FetchOrderHistoryUseCase).to(FetchOrderHistoryUseCase);

});
