export enum TransactionStatus {
    CREATED = "CREATED",
    PENDING = "PENDING",
    PROCESSING = "PROCESSING",
    SUCCESSFUL = "SUCCESSFUL",
    VERIFIED = "VERIFIED",
    FAILED = "FAILED",
    CANCELLED = "CANCELLED",
}
