export enum TransactionStatus {
    CREATED = 'CREATED',
    BLOCKED = "BLOCKED",
    PENDING = "PENDING",
    PROCESSING = "PROCESSING",
    SUCCESSFUL = "SUCCESSFUL",
    // VERIFIED = "VERIFIED",
    FAILED = "FAILED",
    CANCELLED = "CANCELLED",
    REFUNDED = 'REFUNDED',
    REFUND_PENDING = "REFUND_PENDING",
}
